#!/bin/bash

echo "=== GitHub Codespaces Network Setup Guide ==="
echo ""
echo "Your Hardhat node is running in Codespaces, so you need to use the forwarded port URL."
echo ""
echo "1. In VS Code, go to the 'PORTS' tab (next to Terminal)"
echo "2. You should see port 8545 listed"
echo "3. If not visible, click '+' to forward port 8545"
echo "4. Right-click on port 8545 and set visibility to 'Public'"
echo "5. Copy the forwarded URL (it will look like: https://[random-string]-8545.app.github.dev)"
echo ""
echo "Current Codespace info:"
echo "- Hostname: $(hostname)"
echo "- Internal IP: $(hostname -I | awk '{print $1}')"
echo ""
echo "To automatically detect your Codespace URL:"
if [ -n "$CODESPACE_NAME" ]; then
    echo "- Codespace Name: $CODESPACE_NAME"
    CODESPACE_URL="https://${CODESPACE_NAME}-8545.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-app.github.dev}"
    echo "- Predicted RPC URL: $CODESPACE_URL"
    echo ""
    echo "Testing connection to predicted URL..."
    curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_chainId","params":[],"id":1}' "$CODESPACE_URL" 2>/dev/null && echo "✅ Connection successful!" || echo "❌ Connection failed - you may need to make port 8545 public"
else
    echo "- Codespace environment variables not detected"
fi
echo ""
echo "Once you have the correct URL, update the network configuration in MetaMask:"
echo "- Network Name: Hardhat Local"
echo "- RPC URL: [Your forwarded URL]"
echo "- Chain ID: 31337"
echo "- Currency Symbol: ETH"
